server:
  port: 9527
spring:
  application:
    name: cloud-gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
#      default-filters: #全局配置filters
#        - PrefixPath=/httpbin
      routes:
#        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
#          predicates:
#            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
#
#
#        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: lb://cloud-payment-service               #匹配后提供服务的路由地址
#          predicates:
#            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由
#
#        - id: pay_routh3 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: lb://cloud-payment-service                  #匹配后提供服务的路由地址
#          predicates:
#            - Path=/pay/**              # 断言，路径相匹配的进行路由


        - id: pay_routh4
          uri: lb://cloud-payment-service
          predicates:

#          在此时间后可以请求
#            - After=2024-10-26T22:30:49.661818200+08:00[Asia/Shanghai]
#          在此时间前请求
#            - Before=2024-10-26T22:30:49.661818200+08:00[Asia/Shanghai]
#          路由请求规则，只有携带Cookie，键为csk，值为hanson的请求才可以通过
#          在此时间之间
#            - Between=2023-11-21T17:38:13.586918800+08:00[Asia/Shanghai],2023-11-22T17:38:13.586918800+08:00[Asia/Shanghai]
#           请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Header=X-Request-Id, \d+
#           域名以csk.com结尾的请求
#              Host=**.csk.com
#           要有参数名username并且值还要是整数才能路由
#            - Query=username, \d+
#           外部访问我的IP限制，最大跨度不超过32，目前是1~24它们是 CIDR 表示法。
#            - RemoteAddr=192.168.124.1/24
#           方法限制
#            - Method=GET,POST
#            自定义匹配规则，此自定义匹配写法默认不支持短格式，需要进行配置,在自定义配置类1中重写shortcutFieldOrder方法
#            - My=diamond
#            自定义默认匹配规则写法
#            - name: My
#              args:
#                userType: diamond

#            - name: Cookie
#              args:
#                name: csk
#                regexp: hanson
#          filters:
#            - AddRequestHeader=X-Request-atguigu1,atguiguValue1  # 请求头kv，若一头含有多参则重写一行设置
#            - AddRequestHeader=X-Request-atguigu2,atguiguValue2
#            - RemoveRequestHeader=sec-fetch-site      # 删除请求头sec-fetch-site
#            - SetRequestHeader=sec-fetch-mode, Blue-updatebyzzyy # 将请求头sec-fetch-mode对应的值修改为Blue-updatebyzzyy
#            - AddRequestParameter=customerId,9527001 # 新增请求参数Parameter：k ，v
#            - RemoveRequestParameter=customerName   # 删除url请求参数customerName，你传递过来也是null
#            - AddResponseHeader=X-Response-atguigu, BlueResponse # 新增请求参数X-Response-atguigu并设值为BlueResponse
#            - SetResponseHeader=Date,2099-11-11 # 设置回应头Date值为2099-11-11
#            - RemoveResponseHeader=Content-Type # 将默认自带Content-Type回应属性删除
#            - PrefixPath=/pay # http://localhost:9527/pay/gateway/filter,为path前加一个前缀/pay，列如path为，/get/info,则实际匹配地址为/pay/get/info
#            - SetPath=/pay/gateway/{segment}  # {segment}表示占位符，你写abc也行但要上下一致，占位符，列如path如果为，/get/info/{segment}，则实际匹配地址为/get/info/{SetPath}
#            - RedirectTo=302, http://www.atguigu.com/ # 访问http://localhost:9527/pay/gateway/filter跳转到http://www.atguigu.com/，重定向，如果请求地址和path匹配，则重定向



