server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: true
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
#      web-context-unify: false

